/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.enesbalaban.frameler;

import com.enesbalaban.database.*;
import com.enesbalaban.kisiler.*;
import com.enesbalaban.metodİslemlerim.*;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author balab
 */
public class Adminİslemler extends javax.swing.JFrame {

    Veriİslemleri islemler = new Veriİslemleri();
    DefaultTableModel modelDoktor;
    DefaultTableModel modelHasta;
    DefaultTableModel modelPolikinlik;

    /**
     * Creates new form Adminİslemler
     */
    public Adminİslemler() {
        initComponents();
        modelDoktor = (DefaultTableModel) doktorTablosu.getModel();
        modelHasta = (DefaultTableModel) hastaTablosu.getModel();
        modelPolikinlik = (DefaultTableModel) polikinlikTablosu.getModel();
        hastaGoruntule();
        doktorGoruntule();
        polikinlikGoruntule();

    }

    public void doktorGoruntule() {
        modelDoktor.setRowCount(0);

        ArrayList<Doktor> doktorlar = new ArrayList<Doktor>();

        doktorlar = islemler.doktorGetir();

        if (doktorlar != null) {

            for (Doktor doktor : doktorlar) {

                Object[] eklenecek = {doktor.getId(), doktor.getIsim(), doktor.getSoyisim(), doktor.getBolum(), doktor.getTcNo(), doktor.getCinsiyet(), doktor.getEmail(), doktor.getTelefonNo()};

                modelDoktor.addRow(eklenecek);

            }
        }
    }

    public void hastaGoruntule() {

        modelHasta.setRowCount(0);

        ArrayList<Hasta> hastalar = new ArrayList<Hasta>();

        hastalar = islemler.hastaGetir();

        if (hastalar != null) {

            for (Hasta hasta : hastalar) {

                Object[] eklenecek = {hasta.getId(), hasta.getIsim(), hasta.getSoyisim(), hasta.getTcNo(), hasta.getCinsiyet(), hasta.getEmail(), hasta.getTelefonNo(), hasta.getPolikinlik(), hasta.getSaat()};

                modelHasta.addRow(eklenecek);

            }
        }

    }

    public void polikinlikGoruntule() {

        modelPolikinlik.setRowCount(0);

        ArrayList<Polikinlikler> polikinlikler = new ArrayList<Polikinlikler>();

        polikinlikler = islemler.polikinlikGetir();

        if (polikinlikler != null) {

            for (Polikinlikler polikinlik : polikinlikler) {

                Object[] eklenecek = {polikinlik.getId(), polikinlik.getAd(), polikinlik.getKapasite(), polikinlik.getOdaSayisi()};

                modelPolikinlik.addRow(eklenecek);

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        polikinlikTablosu = new javax.swing.JTable();
        polikinlikAramaCubugu = new javax.swing.JTextField();
        polikinlikEkleButon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbPolikinlikAd = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        polikinlikKapasiteAlani = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        polikinlikOdaSayisiAlani = new javax.swing.JTextField();
        polikinlikMesajYazisi = new javax.swing.JLabel();
        polikinlikSilButon = new javax.swing.JButton();
        polikinlikGuncelleButon = new javax.swing.JButton();
        doktorPanel = new javax.swing.JPanel();
        doktorAramaCubugu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        doktorAdAlani = new javax.swing.JTextField();
        doktorSoyadAlani = new javax.swing.JTextField();
        doktorTCAlani = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mesajYazisi = new javax.swing.JLabel();
        doktorEkleButon = new javax.swing.JButton();
        doktorSilButon = new javax.swing.JButton();
        doktorGuncelleButon = new javax.swing.JButton();
        cbDoktorBolum = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbDoktorCinsiyet = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        doktorEmailAlani = new javax.swing.JTextField();
        doktorTelefonAlan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        doktorTablosu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        hastalarAramaCubugu = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        hastaTablosu = new javax.swing.JTable();
        hastaEkleButon = new javax.swing.JButton();
        hastaMesajYazisi = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        hastaAdAlani = new javax.swing.JTextField();
        hastaSoyadAlani = new javax.swing.JTextField();
        hastaEmailAlani = new javax.swing.JTextField();
        cbHastaCinsiyet = new javax.swing.JComboBox<>();
        hastaTelefonAlani = new javax.swing.JTextField();
        cbHastaPolikinlik = new javax.swing.JComboBox<>();
        hastaTcAlani = new javax.swing.JTextField();
        hastaSilButon = new javax.swing.JButton();
        hastaGuncelleButon = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cbSaat = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        polikinlikTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ad", "kapasite", "Oda Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        polikinlikTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                polikinlikTablosuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(polikinlikTablosu);
        if (polikinlikTablosu.getColumnModel().getColumnCount() > 0) {
            polikinlikTablosu.getColumnModel().getColumn(0).setResizable(false);
            polikinlikTablosu.getColumnModel().getColumn(1).setResizable(false);
            polikinlikTablosu.getColumnModel().getColumn(2).setResizable(false);
            polikinlikTablosu.getColumnModel().getColumn(3).setResizable(false);
        }

        polikinlikAramaCubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                polikinlikAramaCubuguKeyReleased(evt);
            }
        });

        polikinlikEkleButon.setText("Polikinlik Ekle");
        polikinlikEkleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polikinlikEkleButonActionPerformed(evt);
            }
        });

        jLabel5.setText("Polikinlik Ad :");

        cbPolikinlikAd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbPolikinlikAd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acil", "KBB", "Dahiliye", "Kan", " " }));

        jLabel6.setText("Kapasite :");

        jLabel7.setText("Oda Sayısı :");

        polikinlikSilButon.setText("Polikinlik Sil");
        polikinlikSilButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polikinlikSilButonActionPerformed(evt);
            }
        });

        polikinlikGuncelleButon.setText("Polikinlik Güncelle");
        polikinlikGuncelleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polikinlikGuncelleButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(polikinlikMesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(polikinlikKapasiteAlani)
                            .addComponent(cbPolikinlikAd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(polikinlikOdaSayisiAlani))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(polikinlikEkleButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(polikinlikSilButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(polikinlikGuncelleButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(polikinlikAramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(polikinlikAramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(polikinlikEkleButon)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cbPolikinlikAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(polikinlikKapasiteAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(polikinlikSilButon))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(polikinlikGuncelleButon)
                    .addComponent(polikinlikOdaSayisiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(polikinlikMesajYazisi)
                        .addGap(343, 343, 343))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(142, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Polikinlikler", jPanel3);

        doktorPanel.setBackground(new java.awt.Color(153, 255, 153));

        doktorAramaCubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                doktorAramaCubuguKeyReleased(evt);
            }
        });

        jLabel1.setText("Ad :");

        jLabel2.setText("Soyad :");

        jLabel3.setText("TC :");

        doktorAdAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorAdAlaniActionPerformed(evt);
            }
        });

        jLabel4.setText("Bölüm :");

        doktorEkleButon.setText("Doktor Ekle");
        doktorEkleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorEkleButonActionPerformed(evt);
            }
        });

        doktorSilButon.setText("Doktor Sil");
        doktorSilButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorSilButonActionPerformed(evt);
            }
        });

        doktorGuncelleButon.setText("Doktor Güncelle");
        doktorGuncelleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorGuncelleButonActionPerformed(evt);
            }
        });

        cbDoktorBolum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acil", "KBB", "Dahiliye", "Beyin Cerrahı" }));

        jLabel8.setText("Cinsiyet :");

        cbDoktorCinsiyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erkek ", "Kız" }));

        jLabel9.setText("Email :");

        jLabel10.setText("Telefon :");

        doktorTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ad", "Soyad", "Bölüm", "TC", "Cinsiyet", "Email", "Telefon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doktorTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doktorTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(doktorTablosu);
        if (doktorTablosu.getColumnModel().getColumnCount() > 0) {
            doktorTablosu.getColumnModel().getColumn(0).setResizable(false);
            doktorTablosu.getColumnModel().getColumn(1).setResizable(false);
            doktorTablosu.getColumnModel().getColumn(2).setResizable(false);
            doktorTablosu.getColumnModel().getColumn(3).setResizable(false);
            doktorTablosu.getColumnModel().getColumn(4).setResizable(false);
            doktorTablosu.getColumnModel().getColumn(5).setResizable(false);
            doktorTablosu.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout doktorPanelLayout = new javax.swing.GroupLayout(doktorPanel);
        doktorPanel.setLayout(doktorPanelLayout);
        doktorPanelLayout.setHorizontalGroup(
            doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doktorPanelLayout.createSequentialGroup()
                .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(doktorPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(doktorAramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(doktorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(doktorAdAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(doktorEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(doktorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doktorPanelLayout.createSequentialGroup()
                                .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbDoktorBolum, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(doktorPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(1, 1, 1)
                                        .addComponent(doktorSoyadAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(112, 112, 112))
                            .addComponent(jLabel4)
                            .addGroup(doktorPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(doktorTCAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doktorSilButon, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doktorGuncelleButon)))
                    .addGroup(doktorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(doktorPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbDoktorCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179)
                                .addComponent(mesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(doktorPanelLayout.createSequentialGroup()
                                .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(doktorPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(doktorTelefonAlan))
                                    .addGroup(doktorPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(doktorEmailAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(71, 71, 71)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(869, Short.MAX_VALUE))
        );
        doktorPanelLayout.setVerticalGroup(
            doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doktorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(doktorPanelLayout.createSequentialGroup()
                        .addComponent(doktorAramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(doktorAdAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doktorEkleButon))
                        .addGap(18, 18, 18)
                        .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(doktorSoyadAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doktorSilButon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbDoktorBolum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doktorPanelLayout.createSequentialGroup()
                        .addComponent(doktorGuncelleButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doktorTCAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbDoktorCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(doktorPanelLayout.createSequentialGroup()
                        .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(doktorEmailAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(doktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(doktorTelefonAlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        jTabbedPane1.addTab("Doktorlar", doktorPanel);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        hastalarAramaCubugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastalarAramaCubuguActionPerformed(evt);
            }
        });
        hastalarAramaCubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hastalarAramaCubuguKeyReleased(evt);
            }
        });

        hastaTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sıra Numarası", "Ad", "Soyad", "TC", "Cinsiyet", "Email", "Telefon No", "Polikinlik", "Saat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hastaTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hastaTablosuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(hastaTablosu);
        if (hastaTablosu.getColumnModel().getColumnCount() > 0) {
            hastaTablosu.getColumnModel().getColumn(0).setResizable(false);
            hastaTablosu.getColumnModel().getColumn(1).setResizable(false);
            hastaTablosu.getColumnModel().getColumn(2).setResizable(false);
            hastaTablosu.getColumnModel().getColumn(3).setResizable(false);
            hastaTablosu.getColumnModel().getColumn(4).setResizable(false);
            hastaTablosu.getColumnModel().getColumn(5).setResizable(false);
            hastaTablosu.getColumnModel().getColumn(6).setResizable(false);
            hastaTablosu.getColumnModel().getColumn(7).setResizable(false);
            hastaTablosu.getColumnModel().getColumn(8).setResizable(false);
        }

        hastaEkleButon.setText("Hasta Ekle");
        hastaEkleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaEkleButonActionPerformed(evt);
            }
        });

        jLabel12.setText("Ad :");

        jLabel13.setText("Soyad :");

        jLabel14.setText("Cinsiyet :");

        jLabel15.setText("Email :");

        jLabel16.setText("Telefon :");

        jLabel17.setText("Polikinlik :");

        jLabel18.setText("TC :");

        cbHastaCinsiyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erkek", "Kız", " " }));

        cbHastaPolikinlik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acil", "KBB", "Dahiliye" }));

        hastaSilButon.setText("Hasta Sil");
        hastaSilButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaSilButonActionPerformed(evt);
            }
        });

        hastaGuncelleButon.setText("Hasta Güncelle");
        hastaGuncelleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaGuncelleButonActionPerformed(evt);
            }
        });

        jLabel11.setText("Saat :");

        cbSaat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08.00", "09.00", "10.00", "11.00", "13.00", "14.00", "15.00", "16.00", "17.00" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(hastalarAramaCubugu, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel11))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(hastaTelefonAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hastaEmailAlani)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hastaMesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(286, 286, 286))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(hastaGuncelleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hastaTcAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cbSaat, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbHastaPolikinlik, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hastaAdAlani)
                                .addComponent(hastaSoyadAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                            .addComponent(cbHastaCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hastaEkleButon, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(hastaSilButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hastalarAramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(hastaAdAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hastaEkleButon))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(hastaSoyadAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cbHastaCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(hastaSilButon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(hastaEmailAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(hastaGuncelleButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hastaMesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(hastaTelefonAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cbHastaPolikinlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSaat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(hastaTcAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Hastalar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doktorAdAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorAdAlaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doktorAdAlaniActionPerformed

    private void doktorEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorEkleButonActionPerformed

        mesajYazisi.setText("");

        ArrayList<Doktor> doktorlarTc = new ArrayList<Doktor>();

        doktorlarTc = islemler.doktorGetir();

        String ad = doktorAdAlani.getText();
        String soyad = doktorSoyadAlani.getText();
        String bolum = (String) cbDoktorBolum.getSelectedItem();
        String tc = doktorTCAlani.getText();
        String cinsiyet = (String) cbDoktorCinsiyet.getSelectedItem();
        String email = doktorEmailAlani.getText();
        String telefonNo = doktorTelefonAlan.getText();

        boolean varmi = true;

        if (!ad.equals("") && !soyad.equals("") && !email.equals("") && !telefonNo.equals("") && !tc.equals("")) {

            for (Doktor doktor : doktorlarTc) {

                if (doktor.getTcNo().equals(tc)) {

                    JOptionPane.showMessageDialog(this, "Zaten randevunuz var...");

                    varmi = false;

                    break;

                }
                if (varmi) {
                    islemler.doktorEkle(ad, soyad, bolum, tc, cinsiyet, email, telefonNo);

                    JOptionPane.showMessageDialog(this, "Randevunuz başarıyla alındı...");

                    doktorAdAlani.setText("");
                    doktorSoyadAlani.setText("");
                    doktorTCAlani.setText("");
                    doktorEmailAlani.setText("");
                    doktorTelefonAlan.setText("");

                }

            }

        } else {

            JOptionPane.showMessageDialog(this, "Lütfen tüm bilgilerinizi girin...");
        }

       


    }//GEN-LAST:event_doktorEkleButonActionPerformed

    private void doktorSilButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorSilButonActionPerformed
        mesajYazisi.setText("");

        int selectedRow = doktorTablosu.getSelectedRow();

        if (selectedRow == -1) {

            if (modelDoktor.getRowCount() == 0) {
                mesajYazisi.setText("Doktor tablosu şuan boş...");
            } else {
                mesajYazisi.setText("Lütfen silinecek bir doktor seçin...");
            }
        } else {

            int id = (int) modelDoktor.getValueAt(selectedRow, 0);

            islemler.doktorSil(id);

            doktorGoruntule();

            mesajYazisi.setText("Doktor başarıyla silindi...");

        }
    }//GEN-LAST:event_doktorSilButonActionPerformed

    private void doktorGuncelleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorGuncelleButonActionPerformed

        String ad = doktorAdAlani.getText();
        String soyad = doktorSoyadAlani.getText();
        String bolum = (String) cbDoktorBolum.getSelectedItem();
        String tc = doktorTCAlani.getText();
        String cinsiyet = (String) cbDoktorCinsiyet.getSelectedItem();
        String email = doktorEmailAlani.getText();
        String telefonNo = doktorTelefonAlan.getText();

        int selectedRow = doktorTablosu.getSelectedRow();

        if (selectedRow == -1) {

            if (modelDoktor.getRowCount() == 0) {

                mesajYazisi.setText("Tabloda hiçbir doktor yok...");
            } else {
                mesajYazisi.setText("Lütfen güncellenecek doktor seçin... ");
            }

        } else {

            int id = (int) modelDoktor.getValueAt(selectedRow, 0);

            islemler.doktorGuncelle(id, ad, soyad, bolum, tc, cinsiyet, email, telefonNo);

            doktorGoruntule();

            mesajYazisi.setText("Doktor başarıyla güncellendi...");

        }
    }//GEN-LAST:event_doktorGuncelleButonActionPerformed

    private void doktorTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doktorTablosuMouseClicked

        int selectedRow = doktorTablosu.getSelectedRow();

        doktorAdAlani.setText(modelDoktor.getValueAt(selectedRow, 1).toString());
        doktorSoyadAlani.setText(modelDoktor.getValueAt(selectedRow, 2).toString());
        cbDoktorBolum.setSelectedItem(modelDoktor.getValueAt(selectedRow, 3).toString());
        doktorTCAlani.setText(modelDoktor.getValueAt(selectedRow, 4).toString());
        cbDoktorCinsiyet.setSelectedItem(modelDoktor.getValueAt(selectedRow, 5).toString());
        doktorEmailAlani.setText(modelDoktor.getValueAt(selectedRow, 6).toString());
        doktorTelefonAlan.setText(modelDoktor.getValueAt(selectedRow, 7).toString());
    }//GEN-LAST:event_doktorTablosuMouseClicked
    public void doktorDinamikAra(String ara) {

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelDoktor);

        doktorTablosu.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void doktorAramaCubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doktorAramaCubuguKeyReleased
        String ara = doktorAramaCubugu.getText();

        doktorDinamikAra(ara);
    }//GEN-LAST:event_doktorAramaCubuguKeyReleased
    public void hastaDinamikAra(String ara) {

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelHasta);

        hastaTablosu.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void hastalarAramaCubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hastalarAramaCubuguKeyReleased
        String ara = hastalarAramaCubugu.getText();

        hastaDinamikAra(ara);
    }//GEN-LAST:event_hastalarAramaCubuguKeyReleased

    private void hastaTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hastaTablosuMouseClicked
        int selectedRow = hastaTablosu.getSelectedRow();

        hastaAdAlani.setText(modelHasta.getValueAt(selectedRow, 1).toString());
        hastaSoyadAlani.setText(modelHasta.getValueAt(selectedRow, 2).toString());
        hastaTcAlani.setText(modelHasta.getValueAt(selectedRow, 3).toString());
        cbHastaCinsiyet.setSelectedItem(modelHasta.getValueAt(selectedRow, 4).toString());
        hastaEmailAlani.setText(modelHasta.getValueAt(selectedRow, 5).toString());
        hastaTelefonAlani.setText(modelHasta.getValueAt(selectedRow, 6).toString());
        cbHastaPolikinlik.setSelectedItem(modelHasta.getValueAt(selectedRow, 7).toString());
    }//GEN-LAST:event_hastaTablosuMouseClicked

    private void polikinlikEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polikinlikEkleButonActionPerformed
        polikinlikMesajYazisi.setText("");

        String ad = (String) cbPolikinlikAd.getSelectedItem();
        String kapasite = polikinlikKapasiteAlani.getText();
        String odaSayisi = polikinlikOdaSayisiAlani.getText();

        islemler.polikinlikEkle(ad, kapasite, odaSayisi);

        polikinlikGoruntule();

        polikinlikMesajYazisi.setText("Yeni polikinlik başarıyla eklendi...");
    }//GEN-LAST:event_polikinlikEkleButonActionPerformed

    private void polikinlikSilButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polikinlikSilButonActionPerformed

        polikinlikMesajYazisi.setText("");

        int selectedRow = polikinlikTablosu.getSelectedRow();

        if (selectedRow == -1) {

            if (modelDoktor.getRowCount() == 0) {
                polikinlikMesajYazisi.setText("Doktor tablosu şuan boş...");
            } else {
                polikinlikMesajYazisi.setText("Lütfen silinecek bir doktor seçin...");
            }
        } else {

            int id = (int) modelPolikinlik.getValueAt(selectedRow, 0);

            islemler.polikinlikSil(id);

            polikinlikGoruntule();

            polikinlikMesajYazisi.setText("Doktor başarıyla silindi...");

        }
    }//GEN-LAST:event_polikinlikSilButonActionPerformed

    private void polikinlikGuncelleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polikinlikGuncelleButonActionPerformed

        String ad = (String) cbPolikinlikAd.getSelectedItem();
        String kapasite = polikinlikKapasiteAlani.getText();
        String odaSayisi = polikinlikOdaSayisiAlani.getText();

        int selectedRow = polikinlikTablosu.getSelectedRow();

        if (selectedRow == -1) {

            if (modelPolikinlik.getRowCount() == 0) {

                mesajYazisi.setText("Tabloda hiçbir polikinlik yok...");
            } else {
                mesajYazisi.setText("Lütfen güncellenecek polikinlik seçin... ");
            }

        } else {

            int id = (int) modelPolikinlik.getValueAt(selectedRow, 0);

            islemler.polikinlikGuncelle(id, ad, kapasite, odaSayisi);

            polikinlikGoruntule();

            polikinlikMesajYazisi.setText("Polikinlik başarıyla güncellendi...");

        }
    }//GEN-LAST:event_polikinlikGuncelleButonActionPerformed
    public void polikinlikDinamikAra(String ara) {

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelPolikinlik);

        polikinlikTablosu.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void polikinlikAramaCubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_polikinlikAramaCubuguKeyReleased
        String ara = doktorAramaCubugu.getText();

        doktorDinamikAra(ara);

    }//GEN-LAST:event_polikinlikAramaCubuguKeyReleased

    private void polikinlikTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polikinlikTablosuMouseClicked
        int selectedRow = polikinlikTablosu.getSelectedRow();

        cbPolikinlikAd.setSelectedItem(modelPolikinlik.getValueAt(selectedRow, 1).toString());
        polikinlikKapasiteAlani.setText(modelPolikinlik.getValueAt(selectedRow, 2).toString());
        polikinlikOdaSayisiAlani.setText(modelPolikinlik.getValueAt(selectedRow, 3).toString());

    }//GEN-LAST:event_polikinlikTablosuMouseClicked

    private void hastaEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaEkleButonActionPerformed

        ArrayList<Hasta> hastalarTc = new ArrayList<Hasta>();

        hastalarTc = islemler.hastaGetir();

        String ad = hastaAdAlani.getText();
        String soyad = hastaSoyadAlani.getText();
        String cinsiyet = (String) cbHastaCinsiyet.getSelectedItem();
        String email = hastaEmailAlani.getText();
        String telefonNo = hastaTelefonAlani.getText();
        String polikinlik = (String) cbHastaPolikinlik.getSelectedItem();
        String tcNo = hastaTcAlani.getText();
        String saat = (String) cbSaat.getSelectedItem();

        boolean varmi = true;

        if (!ad.equals("") && !soyad.equals("") && !email.equals("") && !telefonNo.equals("") && !tcNo.equals("")) {

            for (Hasta hasta : hastalarTc) {

                if (hasta.getTcNo().equals(tcNo)) {

                    JOptionPane.showMessageDialog(this, "Zaten randevunuz var...");

                    varmi = false;

                    break;

                }
                if (hasta.getPolikinlik().equals(polikinlik) && hasta.getSaat().equals(saat)) {

                    JOptionPane.showMessageDialog(this, "Bu polikinlikte seçtiğiniz saat dolu...");

                    varmi = false;

                    break;
                }

            }

            if (varmi) {

                islemler.hastaEkle(ad, soyad, cinsiyet, email, telefonNo, polikinlik, tcNo, saat);

                hastaGoruntule();

                JOptionPane.showMessageDialog(this, "Yeni hasta başarıyla eklendi...");

                hastaAdAlani.setText("");
                hastaSoyadAlani.setText("");
                hastaEmailAlani.setText("");
                hastaTelefonAlani.setText("");
                hastaTcAlani.setText("");
            }
        } else {

            JOptionPane.showMessageDialog(this, "Lütfen hastanın tüm bilgilerini girin...");
        }
    }//GEN-LAST:event_hastaEkleButonActionPerformed

    private void hastaSilButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaSilButonActionPerformed
        hastaMesajYazisi.setText("");

        int selectedRow = hastaTablosu.getSelectedRow();

        if (selectedRow == -1) {

            if (modelDoktor.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Hasta tablosu şuanda boş...");
            } else {
                JOptionPane.showMessageDialog(this, "Lütfen silinecek bir hasta seçin...");
            }
        } else {

            int id = (int) modelHasta.getValueAt(selectedRow, 0);

            islemler.hastaSil(id);

            hastaGoruntule();

            JOptionPane.showMessageDialog(this, "Hasta başarıyla silindi...");

        }
    }//GEN-LAST:event_hastaSilButonActionPerformed

    private void hastalarAramaCubuguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastalarAramaCubuguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hastalarAramaCubuguActionPerformed

    private void hastaGuncelleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaGuncelleButonActionPerformed
        String ad = hastaAdAlani.getText();
        String soyad = hastaSoyadAlani.getText();
        String cinsiyet = (String) cbHastaCinsiyet.getSelectedItem();
        String email = hastaEmailAlani.getText();
        String telefonNo = hastaTelefonAlani.getText();
        String polikinlik = (String) cbHastaPolikinlik.getSelectedItem();
        String tc = hastaTcAlani.getText();
        String saat = (String) cbSaat.getSelectedItem();

        int selectedRow = hastaTablosu.getSelectedRow();

        if (selectedRow == -1) {

            if (modelHasta.getRowCount() == 0) {

                JOptionPane.showMessageDialog(this, "Tabloda hiç hasta yok..");
            } else {
                JOptionPane.showMessageDialog(this, "Lütfen güncellenecek bir hasta seçin...");
            }

        } else {

            int id = (int) modelHasta.getValueAt(selectedRow, 0);

            islemler.hastaGuncelle(id, ad, soyad, cinsiyet, email, telefonNo, polikinlik, tc, saat);

            hastaGoruntule();

            JOptionPane.showMessageDialog(this, "Hasta başarıyla güncellendi..");

        }
    }//GEN-LAST:event_hastaGuncelleButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminİslemler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminİslemler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminİslemler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminİslemler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminİslemler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDoktorBolum;
    private javax.swing.JComboBox<String> cbDoktorCinsiyet;
    private javax.swing.JComboBox<String> cbHastaCinsiyet;
    private javax.swing.JComboBox<String> cbHastaPolikinlik;
    private javax.swing.JComboBox<String> cbPolikinlikAd;
    private javax.swing.JComboBox<String> cbSaat;
    private javax.swing.JTextField doktorAdAlani;
    private javax.swing.JTextField doktorAramaCubugu;
    private javax.swing.JButton doktorEkleButon;
    private javax.swing.JTextField doktorEmailAlani;
    private javax.swing.JButton doktorGuncelleButon;
    private javax.swing.JPanel doktorPanel;
    private javax.swing.JButton doktorSilButon;
    private javax.swing.JTextField doktorSoyadAlani;
    private javax.swing.JTextField doktorTCAlani;
    private javax.swing.JTable doktorTablosu;
    private javax.swing.JTextField doktorTelefonAlan;
    private javax.swing.JTextField hastaAdAlani;
    private javax.swing.JButton hastaEkleButon;
    private javax.swing.JTextField hastaEmailAlani;
    private javax.swing.JButton hastaGuncelleButon;
    private javax.swing.JLabel hastaMesajYazisi;
    private javax.swing.JButton hastaSilButon;
    private javax.swing.JTextField hastaSoyadAlani;
    private javax.swing.JTable hastaTablosu;
    private javax.swing.JTextField hastaTcAlani;
    private javax.swing.JTextField hastaTelefonAlani;
    private javax.swing.JTextField hastalarAramaCubugu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mesajYazisi;
    private javax.swing.JTextField polikinlikAramaCubugu;
    private javax.swing.JButton polikinlikEkleButon;
    private javax.swing.JButton polikinlikGuncelleButon;
    private javax.swing.JTextField polikinlikKapasiteAlani;
    private javax.swing.JLabel polikinlikMesajYazisi;
    private javax.swing.JTextField polikinlikOdaSayisiAlani;
    private javax.swing.JButton polikinlikSilButon;
    private javax.swing.JTable polikinlikTablosu;
    // End of variables declaration//GEN-END:variables

}
